[tool.black]
line-length = 120
target-version = ["py39"]
include = '\.pyi?$'
exclude = '''
/(
    | \.git
    | \.vscode
    | \__pycache__
)/
'''

[tool.isort]
profile = "black"
py_version = 39

[tool.flake8]
exclude = ".git,__pycache__"
select = "C,E,F,W,B,B950"
ignore = "E501, W503"
extend-ignore = "E203"
# see https://lintlyci.github.io/Flake8Rules/

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]

[tool.pycln]
all = true
