[tool.black]
line-length = 120
target-version = ["py39"]
include = '\.pyi?$'
exclude = '''
/(
    | \__pycache__
    | env
)/
'''

[tool.isort]
profile = "black"
skip = "env"
py_version = 39

[tool.flake8]
exclude = "__pycache__,env"
select = "C,E,F,W,B,B950"
max-line-length = 120
ignore = "E501, W503"
extend-ignore = "E203"
# see https://lintlyci.github.io/Flake8Rules/

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]

[tool.pycln]
all = true

[tool.autoflake]
recursive = true
in-place = true
remove-unused-variables = true
remove-rhs-for-unused-variables = true
remove-all-unused-imports = true
ignore-init-module-imports = true
